name: Deploy to Pi

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy with Docker
        run: |
          set -e
          cd /opt/kbx
          git fetch origin
          git reset --hard origin/main
          docker compose build --pull
          docker compose up -d
          docker image prune -f
